/* Metadata heuristics, not pixel classification or cryptographic verification. */
(function(global){
const MAX=1048576,decoder=new TextDecoder();
async function inflate(bytes){if(!global.DecompressionStream)throw Error('瀏覽器無法讀取壓縮中繼資料');const reader=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate')).getReader();let parts=[],size=0;try{while(true){let {value,done}=await reader.read();if(done)break;size+=value.length;if(size>MAX)throw Error('中繼資料超過檢查上限');parts.push(value)}let out=new Uint8Array(size),p=0;for(let part of parts){out.set(part,p);p+=part.length}return out}finally{await reader.cancel().catch(()=>{})}}
function classify(entries,warnings=[]){let reasons=[];for(const {kind,text} of entries){if(/\b(?:trainedAlgorithmicMedia|compositeWithTrainedAlgorithmicMedia)\b/i.test(text))reasons.push(kind+'：宣告 AI 生成或生成式合成');if(/(?:imagined with ai|made with (?:meta )?ai|generated (?:with|by|using) meta ai|meta ai generated)/i.test(text))reasons.push(kind+'：AI 生成文字標記（含 Meta AI）');if(/\b(?:Stable Diffusion|Midjourney|DALL[ -]?E|ComfyUI|AUTOMATIC1111|InvokeAI)\b/i.test(text)||(/Steps:\s*\d+/i.test(text)&&/Sampler:|CFG scale:|Seed:/i.test(text)))reasons.push(kind+'：生成工具或生成參數線索')}return {blocked:reasons.length>0,reasons:[...new Set(reasons)],warnings,metadataCount:entries.length}}
async function inspect(file){const bytes=new Uint8Array(await file.arrayBuffer()),v=new DataView(bytes.buffer),entries=[],warnings=[];let total=0;const text=(kind,b)=>{total+=b.length;if(total>MAX)throw Error('中繼資料超過檢查上限');entries.push({kind,text:decoder.decode(b)})};try{if(bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71){for(let p=8;p+12<=bytes.length;){let n=v.getUint32(p),kind=decoder.decode(bytes.slice(p+4,p+8));if(p+12+n>bytes.length)throw Error('PNG 區塊損毀');let b=bytes.slice(p+8,p+8+n);if(['tEXt','iTXt','zTXt','eXIf','caBX'].includes(kind)){if(n>MAX)throw Error('中繼資料區塊過大');if(kind==='zTXt'){let z=b.indexOf(0);if(z<0||b[z+1]!==0)throw Error('PNG 壓縮文字損毀');text(kind,await inflate(b.slice(z+2)))}else if(kind==='iTXt'){let z=b.indexOf(0);if(z<0)throw Error('PNG 文字損毀');let flag=b[z+1],method=b[z+2],lang=b.indexOf(0,z+3),translated=b.indexOf(0,lang+1);if(lang<0||translated<0||flag>1||method!==0)throw Error('PNG 文字損毀');text(kind,flag?await inflate(b.slice(translated+1)):b.slice(translated+1))}else text(kind,b)}p+=12+n;if(kind==='IEND')break}}
else if(bytes[0]===255&&bytes[1]===216){let p=2;while(p+4<=bytes.length){if(bytes[p++]!==255)throw Error('JPEG 區塊損毀');while(bytes[p]===255)p++;let marker=bytes[p++];if(marker===218||marker===217)break;if(marker===1||(marker>=208&&marker<=215))continue;let n=v.getUint16(p);if(n<2||p+n>bytes.length)throw Error('JPEG 區塊損毀');if([225,235,237,254].includes(marker))text('JPEG metadata',bytes.slice(p+2,p+n));p+=n}}
else if(decoder.decode(bytes.slice(0,4))==='RIFF'&&decoder.decode(bytes.slice(8,12))==='WEBP'){for(let p=12;p+8<=bytes.length;){let kind=decoder.decode(bytes.slice(p,p+4)),n=v.getUint32(p+4,true);if(p+8+n>bytes.length)throw Error('WebP 區塊損毀');if(['XMP ','EXIF','C2PA'].includes(kind))text(kind,bytes.slice(p+8,p+8+n));p+=8+n+(n%2)}}else throw Error('不支援或損毀的圖片容器');}catch(e){warnings.push(e.message)}return classify(entries,warnings)}
global.ArtworkAdmission={inspect,classify};
})(globalThis);
