(function(){const $=id=>document.getElementById(id);let regions=[],start=null,loaded=false;const c=$('faceCanvas');
function rectangle(x,y,w,h){if(![x,y,w,h].every(Number.isFinite)||x<0||y<0||x>=1||y>=1||w<=0||h<=0||w>1||h>1)throw Error('區域座標必須位於圖片內');return {x,y,w:Math.min(w,1-x),h:Math.min(h,1-y)}}
function apply(target){const ctx=target.getContext('2d');for(const r of regions){let x=Math.floor(r.x*target.width),y=Math.floor(r.y*target.height),w=Math.min(target.width-x,Math.max(1,Math.ceil(r.w*target.width))),h=Math.min(target.height-y,Math.max(1,Math.ceil(r.h*target.height)));ctx.save();ctx.globalAlpha=1;if(r.mode==='solid'){ctx.fillStyle=r.color;ctx.fillRect(x,y,w,h)}else{const patch=document.createElement('canvas');patch.width=w;patch.height=h;let pc=patch.getContext('2d');pc.drawImage(target,x,y,w,h,0,0,w,h);ctx.beginPath();ctx.rect(x,y,w,h);ctx.clip();if(r.mode==='pixel'){const small=document.createElement('canvas');let block=Math.max(4,Math.round(r.strength*target.width/960));small.width=Math.max(1,Math.ceil(w/block));small.height=Math.max(1,Math.ceil(h/block));small.getContext('2d').drawImage(patch,0,0,small.width,small.height);ctx.imageSmoothingEnabled=false;ctx.drawImage(small,0,0,small.width,small.height,x,y,w,h)}else{if(!('filter' in ctx)){ctx.fillStyle=r.color;ctx.fillRect(x,y,w,h)}else{ctx.fillStyle=r.color;ctx.fillRect(x,y,w,h);ctx.filter=`blur(${Math.max(4,r.strength*target.width/960)}px)`;ctx.drawImage(patch,x,y,w,h);ctx.filter='none'}}}ctx.restore()}}
function draw(draft){if(!loaded)return;const data=window.ArtworkWorkspace.image();if(!data)return;const full=document.createElement('canvas');full.width=data.width;full.height=data.height;full.getContext('2d').putImageData(data,0,0);let k=Math.min(1,640/data.width);c.width=Math.max(1,Math.round(data.width*k));c.height=Math.max(1,Math.round(data.height*k));let ctx=c.getContext('2d');ctx.drawImage(full,0,0,c.width,c.height);apply(c);for(const r of [...regions,...(draft?[draft]:[])]){ctx.strokeStyle='#c1c5ff';ctx.lineWidth=2;ctx.strokeRect(r.x*c.width,r.y*c.height,r.w*c.width,r.h*c.height)}}
function list(){$('faceRegions').replaceChildren();regions.forEach((r,i)=>{let row=document.createElement('div');row.className='face-region';let text=document.createElement('span');text.textContent=`區域 ${i+1} · ${r.mode==='solid'?'實色遮蔽':r.mode==='pixel'?'馬賽克':'模糊'}`;let b=document.createElement('button');b.textContent='刪除';b.onclick=()=>{regions.splice(i,1);list();draw()};row.append(text,b);$('faceRegions').append(row)});$('faceStatus').textContent=`已設定 ${regions.length} 個區域；請更新公開版預覽。`}
function add(r){if(!window.ArtworkWorkspace.image())throw Error('請先匯入作品');if(regions.length>=30)throw Error('最多 30 個區域');regions.push({...r,mode:$('faceMode').value,color:$('faceColor').value,strength:Number($('faceStrength').value)});list();draw()}
$('faceLoad').onclick=()=>{if(!window.ArtworkWorkspace.image()){$('faceStatus').textContent='請先匯入作品';return}loaded=true;c.hidden=false;draw();$('faceStatus').textContent='拖曳框住臉部，或使用下方百分比欄位新增區域。'};
$('faceAdd').onclick=()=>{try{add(rectangle(Number($('faceX').value)/100,Number($('faceY').value)/100,Number($('faceW').value)/100,Number($('faceH').value)/100))}catch(e){$('faceStatus').textContent=e.message}};
$('faceClear').onclick=()=>{regions=[];list();draw()};function point(e){let r=c.getBoundingClientRect();return {x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))}}function dragged(p){return {x:Math.min(start.x,p.x),y:Math.min(start.y,p.y),w:Math.abs(p.x-start.x),h:Math.abs(p.y-start.y)}}
c.onpointerdown=e=>{if(!loaded)return;start=point(e);c.setPointerCapture(e.pointerId);e.preventDefault()};c.onpointermove=e=>{if(start)draw(dragged(point(e)))};c.onpointerup=e=>{if(!start)return;let r=dragged(point(e));start=null;try{if(r.w*c.width<4||r.h*c.height<4)throw Error('框選區域太小，請重新拖曳');add(rectangle(r.x,r.y,r.w,r.h))}catch(err){$('faceStatus').textContent=err.message;draw()}};c.onpointercancel=()=>{start=null;draw()};window.addEventListener('artwork-loaded',()=>{regions=[];start=null;loaded=false;c.hidden=true;$('publicPreview').hidden=true;list();$('faceStatus').textContent='新作品已載入，請重新框選臉部。'});window.ArtworkPrivacy={apply,rectangle,count:()=>regions.length};list();})();
