(function(){
const fields=['workTitle','workAuthor','workSource','workLicense','licenseNotes','publishPlatform','publishDate','publishURL','caseURL','caseType','caseStatus','caseDate','caseNotes'];let records=[],currentId=null;const el=id=>document.getElementById(id);
function dimensions(w,h,max){if(!Number.isFinite(w)||!Number.isFinite(h)||w<=0||h<=0||![640,960,1280].includes(max))throw Error('Invalid dimensions');let ratio=Math.min(1,max/Math.max(w,h));return {width:Math.max(1,Math.round(w*ratio)),height:Math.max(1,Math.round(h*ratio))}}
function safeURL(s){if(!s)return true;try{return ['https:','http:'].includes(new URL(s).protocol)}catch{return false}}
function validate(raw){if(!raw||raw.format!=='artwork-rights-v1'||!Array.isArray(raw.records)||raw.records.length>500)throw Error('不是有效的作品紀錄備份（最多 500 筆）');let ids=new Set();return raw.records.map(r=>{if(!r||typeof r.id!=='string'||!r.id||r.id.length>100||ids.has(r.id))throw Error('紀錄 ID 無效或重複');ids.add(r.id);let clean={id:r.id};for(let f of fields){if(typeof r[f]!=='string'||r[f].length>5000)throw Error('紀錄欄位無效');clean[f]=r[f]}if(!clean.workTitle.trim()||!clean.workAuthor.trim()||!clean.workSource.trim())throw Error('缺少作品名稱、作者或來源');if(!safeURL(clean.publishURL)||!safeURL(clean.caseURL))throw Error('只允許 http / https 網址');return clean})}
function draft(r){const t=s=>window.ArtworkI18n?.tr(s)||s;const pairs=[['作品',r.workTitle],['作者／權利人',r.workAuthor],['來源與證明',r.workSource],['授權範圍',t(r.workLicense)],['授權細節',r.licenseNotes],['平台',t(r.publishPlatform)],['原發布日期',r.publishDate],['原發布網址',r.publishURL],['疑似使用網址',r.caseURL],['處理事項',t(r.caseType)],['進度',t(r.caseStatus)],['處理日期',r.caseDate],['證據／案件回覆',r.caseNotes]];return [t('作品使用／申訴資料草稿（請人工核對，不會自動送出）'),' ',...pairs.map(([label,value])=>t(label)+': '+(value||t('未填'))),' ',t('請平台檢視上述作品的資料使用、授權或疑似未授權使用情況，並告知可採取的處理方式。'),' ',t('送出前：核對權利歸屬、既有授權與平台要求；補充所需聯絡資訊及證明。這份草稿不包含法律宣誓，也不表示平台已接受請求。'),t('整理時間')+': '+new Date().toISOString()].join('\n')}
window.ArtworkRightsHelpers={dimensions,validate,draft};
function message(s){el('recordMessage').textContent=s}function download(content,type,name){let url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000)}
function readForm(){let r={id:currentId||crypto.randomUUID()};for(let f of fields)r[f]=el(f).value.trim();return validate({format:'artwork-rights-v1',records:[r]})[0]}
function showRecords(){el('recordList').replaceChildren();if(!records.length){el('recordList').textContent='尚無紀錄。';return}for(let r of records){let box=document.createElement('div');box.className='record-item';let title=document.createElement('strong');title.textContent=r.workTitle;let meta=document.createElement('small');meta.textContent=r.publishPlatform+' · '+r.caseType+' · '+r.caseStatus;let edit=document.createElement('button');edit.textContent='編輯';edit.onclick=()=>{currentId=r.id;for(let f of fields)el(f).value=r[f];message('正在編輯：'+r.workTitle);el('workTitle').focus()};let del=document.createElement('button');del.textContent='刪除';del.onclick=()=>{if(!confirm('刪除此頁的紀錄？已下載的備份不會改變。'))return;records=records.filter(x=>x.id!==r.id);if(currentId===r.id)newRecord();showRecords();message('已刪除；請下載新的備份。')};box.append(title,meta,edit,del);el('recordList').append(box)}}
function newRecord(){currentId=null;el('recordForm').reset();el('workTitle').value=window.ArtworkWorkspace.name()==='artwork'?'':window.ArtworkWorkspace.name();el('workAuthor').value=document.getElementById('owner').value;message('新增紀錄；請填寫作品來源。')}
el('newRecord').onclick=newRecord;el('recordForm').onsubmit=e=>{e.preventDefault();try{let r=readForm();if(!currentId&&records.length>=500)throw Error('最多保存 500 筆，請先備份');let i=records.findIndex(x=>x.id===r.id);if(i<0)records.push(r);else records[i]=r;currentId=r.id;showRecords();message('已保存到本頁；請下載 JSON 備份以永久保存。')}catch(e){message(e.message)}};
el('exportRecords').onclick=()=>download(JSON.stringify({format:'artwork-rights-v1',exportedAt:new Date().toISOString(),records},null,2),'application/json','artwork-rights-backup.json');el('importRecords').onclick=()=>el('recordsFile').click();el('recordsFile').onchange=async e=>{let file=e.target.files[0];if(!file)return;try{if(file.size>5*1024*1024)throw Error('備份超過 5 MB');let incoming=validate(JSON.parse(await file.text()));if(records.length&&!confirm('匯入會替換本頁紀錄，請先下載現有備份。繼續？'))return;records=incoming;newRecord();showRecords();message('已匯入 '+records.length+' 筆紀錄。')}catch(err){message('匯入失敗：'+err.message)}finally{e.target.value=''}};
el('exportCase').onclick=()=>{try{let r=readForm();download(draft(r),'text/plain;charset=utf-8','artwork-case-draft.txt');message('已下載草稿；請核對後自行在平台送出。')}catch(e){message(e.message)}};
function publicCanvas(){const data=window.ArtworkWorkspace.image();if(!data)throw Error('請先匯入作品');let text=el('publicText').value.trim();if(!text)throw Error('請填寫可見水印文字');let {width,height}=dimensions(data.width,data.height,Number(el('publicSize').value));const full=document.createElement('canvas');full.width=data.width;full.height=data.height;full.getContext('2d').putImageData(data,0,0);const c=el('publicPreview');c.width=width;c.height=height;let ctx=c.getContext('2d');ctx.clearRect(0,0,width,height);ctx.drawImage(full,0,0,width,height);window.ArtworkPrivacy.apply(c);const position=el('publicPosition').value;let size=Math.max(8,Math.min(32,width/22));ctx.font=`600 ${size}px system-ui`;let avail=width*.85;while(ctx.measureText(text).width>avail&&size>1){size-=.5;ctx.font=`600 ${size}px system-ui`}ctx.globalAlpha=Number(el('publicOpacity').value)/100;ctx.textAlign='center';ctx.textBaseline='middle';let band=size*2.2;function stamp(x,y){ctx.fillStyle='#080b20';ctx.fillRect(x-width*.45,y-band/2,width*.9,band);ctx.fillStyle='white';ctx.fillText(text,x,y)}if(position==='tile'){for(let y=height*.18;y<height;y+=Math.max(band*2.4,height*.28))stamp(width/2,y)}else stamp(width/2,position==='bottom'?Math.max(band/2,height-band*.8):height/2);ctx.globalAlpha=1;c.hidden=false;el('publicDimensions').textContent=`公開版本：${width} × ${height} px · ${position==='tile'?'全圖重複':position==='center'?'中央':'底部'}水印`;return c}
el('previewPublic').onclick=()=>{try{publicCanvas()}catch(e){el('publicDimensions').textContent=e.message}};el('downloadPublic').onclick=()=>{try{let c=publicCanvas();c.toBlob(blob=>{if(!blob){el('publicDimensions').textContent='PNG 匯出失敗';return}download(blob,'image/png','artwork-public-watermarked.png')},'image/png')}catch(e){el('publicDimensions').textContent=e.message}};showRecords();
})();
